version: "3"

services:
  react-notifications:
    image: node:lts-slim
    command: sh -c "npm install && npm run build"
    restart: always
    working_dir: /usr/app
    ports:
      - "8095:3000"
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
